# -*- coding: utf-8 -*-
"""actividadsept_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEFNW0_n1HKedyU9U5ygphwaEM7AlcjK
"""

# pasar de binario a Decimal
print('De binarios a decimales :)')
a="10011110"
a=int(a,2)
c="00010001"
c=int(c,2)
d="00100110"
d=int(d,2)
e="1110"
e=int(e,2)
f="11011101110"
f=int(f,2)
g="10110110"
g=int(g,2)
h="0"
h=int(h,2)
i="10"
i=int(i,2)
j="1"
j=int(j,2)
print (a,"\n",c,"\n",d,"\n",e,"\n",f, "\n",g,"\n",h,"\n",i,"\n",j)

#Pasar de Decimal a Binario
print(' ')
print("De decimal a binarios :)")

k=32
k=int(bin(k)[2:])
l=147
l=int(bin(l)[2:])
m=43
m=int(bin(m)[2:])
n=80
n=int(bin(n)[2:])
o=7512
o=int(bin(o)[2:])
p=145
p=int(bin(p)[2:])
q=1
q=int(bin(q)[2:])
r=0
r=int(bin(r)[2:])
s= 19
s=int(bin(s)[2:])
w= print (k,"\n",l,"\n",m,"\n",n,"\n",o,"\n",p,"\n",q,"\n",r,"\n",s)

#Conjuntos
#NOTA: Cuando son palabras todo va en comillas
A={1,"a",2,"b",3,"c"}
B={4,"c",5,"b",2,"d"}
#Union
print(' ')
print('Union')
print(' ')
print(A|B)
print(A.union(B))
print(' ')
#intersección
print(' ')
print('interseccion')
print(' ')
print(A&B)
print(A.intersection(B))
print(' ')
#Diferencia Simetrica
print('diferencia simetrica')
print(' ')
print(A^B)
print(A.symmetric_difference(B))
#Diferencia
print(' ')
print('Diferencia')
print(' ')
print(A-B)
print(A.difference(B))