# -*- coding: utf-8 -*-
"""Icfes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsCsdvK-nUy4QPWJt3a58AlV6Obj2GX6
"""



print(' Mencione los dos primeros de la punta sobre la cadena alimenticia ')
A=print('A.productores')
B=print('B.carroñeros')
C=print('C.carnívoros ')
D=print('D. consumidores primarios')
R1=input('ingrese la primera respuesta: ')
R2=input('Ingrese la segunda Respuesta:')
print('')
if R1 and R2== 'B' and 'C':
  print('Correcto')
else:
  print('incorrecto')

if R2 and R1== 'C' and 'B':
    print('correcto')
else:
  print('incorrecto')



PREGUNTA=print('¿Cómo se oxigena el cuerpo humano durante la respiración')
A=print('A. En los pulmones el oxígeno inspirado pasa a la sangre.')
B=print(' B. Los pulmones almacenan el oxígeno que se está inspirando.')
C=print('C. Los pulmones aumentan el oxígeno que tiene el aire inspirado.')
D= print(' D. En los pulmones el dióxido de carbono inspirado se transforma en oxígeno.')
print(' ')
RESPUESTA=input('Ingrese la Respuesta :')
if RESPUESTA =='A':
    print(' Corecto')
else :
    print('incorrecto')
print(' ')
SEGUNDA= print('''En una especie de planta el color rojo de los pétalos de las flores es
dominante sobre el color blanco. Al cruzar una planta heterocigota de flores
rojas con una planta de flores blancas, ¿cuál será la proporción de su
descendencia?''')
A= print(' A. 100% de plantas con flores rojas')
B=print( ' B. 75% de plantas con flores rojas; 25% de plantas con flores blancas')
C=print(' C. 50% de plantas con flores rojas; 50% de plantas con flores blancas')
D= print(' D. 25% de plantas con flores rojas; 75% de plantas con flores blancas')
print(' ')
RESPUESTA=input(' Ingrese la que crea correcta: ')
if RESPUESTA== 'C' :
    print(' Correcta')
else:
    print(' incorrecto')
print(' ')
print(''' 3 La enterocolitis es una enfermedad infecciosa del sistema digestivo,
generalmente causada por alguna bacteria. Se presenta como una
inflamación que afecta a la mucosa del intestino, provocando diarrea y dolores
abdominales.
¿De qué manera se puede prevenir la enterocolitis?''')

A=print(' A. Comiendo frutas y verduras de preferencia.')
B= print(' B. Utilizando solamente servicio desechable para comer.')
C= print('C. Lavándose bien las manos antes de manipular alimentos.')
D= print('D. Agregando sal suficiente al alimento para matar a los microbios. ')
print(' ')
R2=input('Ingrese la respuesta:')
if R2 == 'C':
    print('Correcta')
else:
    print('incorrecto')
print(' ')

print('ingresa a este link: (http://1.bp.blogspot.com/-UUk7aNrvhzM/UBMcANwUGWI/AAAAAAAAAlY/hcJpj8p1xxI/s1600/cadena+alimenticia+marino+grupo+kepler.cta1.PNG')
print('De acuerdo a la imagen, ¿qué organismo actúa como consumidor primario?')
A= print('A. Alga')
B= print('B. Caracol Marino.')
C= print('C. Pez.')
D= print('D. León Marino')
print('')
R3= input('Ingrese su respuesta:')
if R3 =='B':
    print('Correcto')
else:
    print('incorrecto')
print('')

print('''Claudia pone una cuchara metálica frente al vapor que sale de una tetera
donde hierve agua. Ella observa que en la cuchara el vapor se condensa y
aparecen pequeñas gotas de agua.
¿Qué le ocurre a las partículas de vapor cuando éste se condensa?''')
A = print('A. Disminuyen su movimiento.')
B =print('B. Aumentan su temperatura.')
C =print('C. Aumentan de tamaño.')
D =print('D. Disminuyen su masa.')
print('')
R4= input('Ingrese su respuesta:')
if R4=='A':
    print('Correcto')
else:
    print('incorrecto')
print('')

print(''' Cuando las personas viajan a lugares de gran altitud pueden sufrir dolor
de cabeza y mareos debido a los cambios en la atmósfera. ¿Qué cambios se
producen en la atmósfera al aumentar la altitud geográfica?''')
A =print('A. Aumenta la temperatura del aire.')
B =print('B. Disminuye la presión del oxígeno')
C =print('C. Aumenta la densidad de la atmósfera')
D =print('D. Disminuye la circulación de aire atmosférico.')
print('')
R5= input('Ingrese su respuesta:')
if R5=='B':
    print('Correcto')
else:
    print('incorrecto')
print('')
print(''' De acuerdo al modelo cinético molecular de los gases, ¿por qué al
calentar el aire contenido en un globo, aumenta de tamaño?''')
A=print(' A. Porque aumenta la velocidad de las partículas de aire')
B=print(' B. Porque aumenta el tamaño de las partículas de aire.')
C=print(' C. Porque aumenta la cantidad de partículas de aire.')
D=print (' D. Porque aumenta la masa de las partículas de aire.')
print(' ')
RESPUESTA=input(' ingrese la respuesta: ')
if RESPUESTA=='A':
    print(' Correcto')
else:
    print(' incorrecto')
    print(' ')
print('¿Qué tres partes se distinguen en el cuerpo humano?')
A=print('A.Cabeza, piernas y brazos')
B=print(' B. Cuerpo, piernas y brazos')
C=print(' C.Cabeza, tronco y extremidades')
RESPUESTA=input('Ingrese la respuesta:')
if RESPUESTA== 'C':
    print(' Correcto')
else:
    print('incorrecto')
print(' ')
print('¿Cuáles son las funciones vitales de los seres humanos?')
A=print(' A. Nutrición y reproducción.')
B= print(' B.  Nacer, crecer y morir.')
C= print('C.  Reproducción, relación y nutrición.')
print(' ')
RESPUESTA=input('Ingrese la respuesta:')
if  RESPUESTA== 'C' :
    print(' Correcto')
else:
    print('incorrecto')
print(' ')
print('¿Cuál es la ciencia que estudia las estrellas?')
A=print('A.Gastronomia')
B=print('B.Astronomia')
C= print('C. Astrología')
print(' ')
RESPUESTA=input('Ingrese la respuesta : ')
if RESPUESTA== ' B':
    print(' Correcto')
else:
    print(' incorrecto')
print(' ')
print('¿Qué dos tipos de carga eléctrica existen?')
A= print('A.arga rápida y carga lenta')
B= print('B.arga rápida y carga lenta')
C=print(' C.Carga vertical y carga horizontal.')
print(' ')
RESPUESTA=input(' Ingrese las respuesta:')
if RESPUESTA=='B':
    print(' Correcto')
else:
    (' incorrecto')

print(' ')

print(' El oxígeno que se desprende durante la fotosíntesis procede de')
A=print(' a- La molécula de agua')
B= print(' b- La molécula de CO2')
C=print(' c- La molécula de clorofila')
D=print(' d- La atmósfera')
print(' ')
RESPUESTA=input('Ingrese la respuesta')
if RESPUESTA== 'A':
    print('Correcto')
else:
    print('incorrecto')
print(' ')

print(' Mencione los dos primeros de la punta sobre la cadena alimenticia ')
A=print('A.productores')
B=print('B.carroñeros')
C=print('C.carnívoros ')
D=print('D. consumidores primarios')
RESPUESTA=input('ingrese las respuestas: ')
print('')
if RESPUESTA== 'B and C'
C':
    print('Correcto')
else:
    print('incorrecto')