# -*- coding: utf-8 -*-
"""Menu Geometrico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFD6vsCp3F7XjGQY-YnBYDnSJ5JX4WqS
"""

print("\033[3;36m")
while True:
  print('1.rectangulo')
  print('2.triangulo')
  print('3.circulo')
  print('4.salir')

  a=input('Escoge una opcion:')
  if a=="1":
    rectangulo()
  elif a=="2":
    triangulo()
  elif a=="3":
    circulo()
  elif a=="4":
     break

def rectangulo():
  while True:
    print("\033[3;33m")
    A=(input('ingresa el ancho de un rectangulo: '))
    B=(input('ingresa la altura de un rectangulo: '))
    if A.isdigit() and B.isdigit():
      A=int(A)
      B=int(B)
      break
    else:
      print('error de ingreso ')
  R=A*B
  P=2*A+2*B
  from tabulate import tabulate
  table=[["perimetro",P],["radio", R]]
  print (tabulate(table,tablefmt="grid"))
rectangulo()

def circulo():
  while True:
    A=(input('ingresa el radio de una circunferencia: '))
    if A.isdigit():
      A=int(A)
      break
    else:
      print('error de ingreso ')
  P=2*3.14*A
  R=3.14*(A**2)
  from tabulate import tabulate
  table=[["perimetro",P],["radio", R]]
  print (tabulate(table,tablefmt="grid"))
circulo()

#Realizar un programa que pida al usuario las medidas de los 3 lados de un triangulo y nos devuelva su perímetro y su area.
def triangulo():
  print("\033[0;36m")
  print('Hola, con este programa descubriremos el area y perimetro de tu triangulo solo con sus lados, por favor responder:')
  while True:
    M=(input('Ingresa el primer lado: '))
    N=(input('Ingresa el segundo lado: '))
    C=(input('Ingresa el tercer lado: '))
    if M.isdigit() and N.isdigit() and C.isdigit() :
      M=int(M)
      N=int(N)
      C=int(C)
      break
    else:
      print('error de ingreso')
  if(M==N and N==C):
      a=(' Equilatero')
  elif(M==N or M==C or C==M):
      a=('Isoceles')
  else:
    a=('Escaleno')

  P=M+C+N
  S=P/2
  x=S*(S-M)*(S-N)*(S-C)
  A=pow(x,0.5)
  from tabulate import tabulate
  table=[["Perimetro",P],["Subperimetro",S],["Area",A],["Tipo de triangulo", a]]
  print(tabulate(table,tablefmt="grid"))

triangulo()