# -*- coding: utf-8 -*-
"""Operadoreslogicos (12/05/2022).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vp8SehuebfavxLIMQQNkwp_4836-gpq

# **ACTIVIDAD #1**

**Punto 1**
"""

print ('buenassssss, Tres numeros enteros y diferentes ')
print('')
NUM1=int(input('PRIMER NÚMERO:'))
NUM2=int(input('SEGUNDO NÚMERO:'))
NUM3=int(input('TERCER NÚMERO:'))
print('')
if NUM1>NUM2 and NUM1>NUM3:
  print('Mor este número es mayor')
  print(NUM1)
else:
  if NUM2>NUM1 and NUM2>NUM3:
    print('Mor este número es mayor')
    print(NUM2)
  else:
    print('Mor este número es mayor')
    print(NUM3)

"""**Punto 2**"""

LISTA=['lavar','Cocinar','Barrer','Trapear','Sacudir','Doblar ropa',]
SUMA=0
print('Por favor ingrsa un "1" sirealizaste la tarea o un "0"')
for i in LISTA :
  print('Las tareas a realizar son:', i)
  SN=int(input())
  SUMA+=SN
if SUMA >= 3:
  from tabulate import tabulate
  table=[["Vamonos para guatape como recompensa ^^"]]
  print("\033[3;33;49m")
  print(tabulate(table,tablefmt="grid"))
else:
  print('Te quedas por marika,siga sin ayudar en la casa')

"""°Santiago Giraldo Tapasco
°Shadai Jimena Mazo Mestra      1101
 °Ana Maria Arena Hoyos

**Punto 2 con and**
"""

LISTA=['lavar','Cocinar','Barrer','Trapear','Sacudir','Doblar ropa',]
TAREAS=['artistica','quimica','estadistica','fisica','biologia','religion']
SUMA1=0
SUMA2=0
print('Por favor ingresa un "1" si realizaste el oficio o un "0" si no')
print('')
for i in LISTA :
  print('Los oficios a realizar son:', i)
  SN=int(input())
  SUMA1+=SN
print('')
print('Para completar ingresa un "1" si realizaste la tarea o un "0" si no')
print('')
for i in TAREAS :
  print('Las tareas a realizar son:', i)
  NS=int(input())
  SUMA2+=SN
if SUMA1>=3 and SUMA2>=3 :
  from tabulate import tabulate
  table=[["Vamonos para guatape como recompensa ^^"]]
  print("\033[3;33;49m")
  print(tabulate(table,tablefmt="grid"))
else:
  print('Te quedas por marika,siga sin ayudar en la casa')

"""# **ACTIVIDAD #2**"""

DIA=int(input('Ingrese el día:'))
MES=(input('Ingrese el mes:'))
AÑO=int(input('Ingrese el año:'))
if MES=='enero' or MES=='febrero' or MES=='marzo':
  print('Esta fecha es del primer trimestre')
elif  MES=='abril' or MES=='mayo' or MES=='junio':
  print('Esta fecha es del segundo trimestre')
elif MES=='julio' or MES=='agosto' or MES=='septiembre':
  print('Esta fecha es del tercer trimestre')
elif  MES=='octubre' or MES=='noviembre' or MES=='diciembre':
  print('Esta fecha es del cuarto trimestre')
else:
  print('Mor ¿esa fecha de dónde salio? que no la conozco')

"""## ACTIVIDAD #3
Identifique si es AND ó OR
-Realice un programa que le pida al usuario ingresar una fecha y que indique si es año biciesto
  R/= Ambas :)

"""