# -*- coding: utf-8 -*-
"""Pizzeria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvPnD72Uscb3c7XZ46qbnjzi6gtjNmRl
"""

int(input("Hola, bienvenido a Bella Napoli pizza, Si deseas una pizza vegetariana Escribe 1 en contrario Escribe 2 : "))

if(q==1):
  print("Los Sabores son :  Pimenton y Tofu , recuerdo solo puedes agregar 1 sabor ademas del tomate y el queso :p")
  v=int(input("Si deseas pimenton ingresa 1, Si deseas tofu marca 2: "))
  if(v==1):
    print("Tu Pizza es vegetariana esta contiene: Queso, Mozarella y Pimenton ")
  elif(v==2):
    print("Tu Pizza es vegetariana esta contiene: Queso, Mozarella y Tofu ")
  else:
    print("Lee bien las instrucciones dadas")
elif(q==2):
   print("Los Sabores son : peperoni, jamon y Salmón , recuerdo solo puedes agregar 1 sabor ademas del tomate y el queso :p")
   n=int(input("Si deseas peperoni ingresa 1, Si deseas jamon marca 2 o si deseas salmon marca 3: "))
   if(n==1):
      print("Tu Pizza es normal y esta contiene: Queso, Mozarella y Peperoni ")
   elif(n==2):
      print("Tu Pizza es normal y esta contiene: Queso, Mozarella y jamon ")
   elif(n==3):
      print("Tu pizza es normal y esta contiene: Queso, Mozarella y Salmon")
   else:
      print("Lee bien las instrucciones dadas")
else:
  print("Lee bien las instrucciones dadas")