# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXXtjjnPwaqUchFWNpOjMCxUGuykYW84
"""

ICECREAM= float(input("Ingrese la temperatura: "))

if (ICECREAM>=27):
  print("Puedes Comprar helado ¿Ya viste la temperatura? es de", ICECREAM )
else:
  print("Mejor compremos un jugo de naranja")

print("fin del programa")

ICECREAM= float(input("Ingrese la temperatura: "))

if (ICECREAM>26):
  print("Puedes Comprar helado ¿Ya viste la temperatura? es de", ICECREAM )
elif (ICECREAM<16):
  print("raro mira este frio, tomate un chocolate")
else:
  print("Mejor compremos un jugo de naranja")

print("fin del programa")

EDAD= int(input("Ingrese su edad: "))

if (EDAD>=18):
  DINERO=int(input("Ingrese el dinero: " ))
  if (DINERO>=10):
    print("Puedes entrar al Teatro")
  else:
    print("No puedes entrar")
else:
  print("No cumples con la edad")
print("Fin Programa")

VV= int(input("Ingrese la cantidad de votos validos: "))
VP= int(input("ingrese la cantidad de votos de tu partido: "))

TOTAL= VP*0.03

if (VP>TOTAL) :
  print("Tu partido tendrá curules")
else:
  print("Se quemaron")