# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KueyissDw0xqR7Xqt6Vb8hHXP5c9iQj6
"""

i=1
while (i<=10):
  print("Bienvenido blah blah")
  i=i+2
print("fin")

i=10
while (i>=0):
  print("Bienvenido blah blah")
  i=i-2
print("fin")

i=1
while (i<6):
  if (i==5):
    print("hola")
  i=i+2

print("fin")

i=5
while (i<=15):
  print("Bienvenido blah blah")
  i=i+5
print("fin")

"""1 iniciar la variable del ciclo

2 evaluar si la condicion del ciclo se cumple

3 cuerpo del ciclo = codigo que se ejecuta dentro del ciclo (if,elif,else)

4 actualizacion de la variable del ciclo

LOGICA ( AND OR )

indentacion( espacio)  

- - - - - - (Ram interno)    _________ (Visual de colab)


!= diferente



"""