# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8v0qWkoeKqnSuyuc-dJNSP4-vnwVer1
"""

a=input(("¿Desea continuar el programa?: "))
while a == "sí":
  print("Intente de nuevo")
  a=input(("¿Desea continuar el programa?: "))

print("Gracias")

frase = input("Por favor, ingrese una frase (o escriba 'fin' para detenerse): ")
while len(frase) >0 and frase [-1]== ".":
  print("Frase finalizada con punto.")
  frase = input("Por favor, ingrese una frase (o escriba 'fin' para detenerse): ")

print("No finaliza con punto.")

dic=["a", "e", "i", "o", "u"]
palabra = input (" Por favor , ingrese la palabra que desea analizar : ")
while len(palabra)> 0:
  if palabra == dic:
    print("Tiene vocales")
    break
print("chao")

palabra = input("Por favor, ingrese una palabra en minúsculas y sin tildes: ")

indice = 0

tiene_a = False
tiene_e = False
tiene_i = False
tiene_o = False

while indice < len(palabra):

    letra = palabra[indice]


    if letra == 'a':
        tiene_a = True
    elif letra == 'e':
        tiene_e = True
    elif letra == 'i':
        tiene_i = True
    elif letra == 'o':
        tiene_o = True
    elif letra == 'u':
        tiene_u = True

    # Incrementar el índice para pasar a la siguiente letra
    indice += 1

# Imprimir el resultado para cada vocal
print(f'a: {"SI" if tiene_a else "NO"}')
print(f'e: {"SI" if tiene_e else "NO"}')
print(f'i: {"SI" if tiene_i else "NO"}')
print(f'o: {"SI" if tiene_o else "NO"}')
print(f'u: {"SI" if tiene_u else "NO"}')

# Pedir al usuario que ingrese la palabra para el coro con signos de exclamación al principio y al final
coro = input("Ingrese la palabra para el coro (con ! al principio y al final): ")

# Verificar que la palabra comience y termine con signos de exclamación
if len(coro) >= 2 and coro[0] == '!' and coro[-1] == '!':
    # Inicializar un índice para recorrer la palabra (excluyendo los signos de exclamación)
    indice = 1

    # Mientras el índice esté dentro de los límites de la palabra
    while indice < len(coro) - 1:
        # Obtener la letra actual
        letra = coro[indice]

        # Imprimir la letra
        print(letra, end=" ")

        # Incrementar el índice para pasar a la siguiente letra
        indice += 1

    # Salto de línea al final
    print()
else:
    print("La palabra para el coro debe comenzar y terminar con signos de exclamación.")

password = input("Ingrese Por Favor Su Contaseña:  ")
intentos=0
while intentos<3:
  a=input("Ingrese De nuevo la contraseña: ")
  if  password==a:
    print("Contraseña correcta")
    break
  else:
    print("Contraseñas no coinciden")
    intentos+=1
if intentos ==3:
  print("Fin del programa")

for i in range(5, 0, -1):
    for j in range(i, 0, -1):
        print(j, end="")
    print()

for num in range(2, 101):
    es_primo = True  # Suponemos que el número es primo hasta que se demuestre lo contrario

    # Verificar si el número es primo
    for i in range(2, int(num*0.5) + 1):
        if num % i == 0:
            es_primo = False
            break

    # Si es un número primo, lo imprimimos
    if es_primo:
        print(num, end=" ")

si=input("Ingrese su contraseña: ")
while len(si)>0:
  no=input("ingrese nuevamente su contraseña: ")
  if si==no:
    print("Contraseñas coincides")
    break
  print("Contraseñas no coinciden")
  no=input("ingrese nuevamente su contraseña: ")
print("Hasta luego")

money = int(input("Cuanto dinero desea ahorrar : "))
hucha=0
while money >0:
  if hucha==0:
    a= int(input("Cuanto dinero desea ingresar: "))
    hucha+=a
    a= int(input("Cuanto dinero desea ingresar: "))
  elif hucha==money:
    print("Felicidades lograste ahorrar")
    break
print("Fin del programa")